### ISSUE TITLE
Does not work with 11.3

### ISSUE THREAD

**Issue by RobotWizard11** [games50/breakout#6]
I have tried to run Breakout with Love 2D 11.3 but I get error message: 
 
Error main.lua:73: bad argument #2 to 'newSource' (string expected, got no value)

Traceback

[C]: in function 'newSource'
main.lua:73: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

![error message](https://user-images.githubusercontent.com/64268416/81114599-40f5e580-8f1a-11ea-8f39-6a4396cecbad.jpeg)

Can anyone help?

**Comment by edischin** [comment]
'newSource' function demands a second parameter with the SourceType, which in this case would be 'static':
https://love2d.org/wiki/love.audio.newSource
