### ISSUE TITLE
Unable to see the blue text on the menu screen (breakout1)

### ISSUE THREAD

**Issue by RobotWizard11** [games50/breakout#7]
When I press up or down I am unable to see the text turn blue.
![no blue text](https://user-images.githubusercontent.com/64268416/81208563-2f1e4c00-8fc7-11ea-9706-4ff1f118391f.png)

**Comment by YouLate** [comment]
You just need to change the 103 red value to 0, It worked for me 


function StartState:render()
    -- title
    love.graphics.setFont(gFonts['large'])
    love.graphics.printf("BREAKOUT", 0, VIRTUAL_HEIGHT / 3,
        VIRTUAL_WIDTH, 'center')
    
    -- instructions
    love.graphics.setFont(gFonts['medium'])

    -- if we're highlighting 1, render that option blue
    if highlighted == 1 then
        love.graphics.setColor**(0, 255, 255, 255)**
    end
    love.graphics.printf("START", 0, VIRTUAL_HEIGHT / 2 + 70,
        VIRTUAL_WIDTH, 'center')

    -- reset the color
    love.graphics.setColor(255, 255, 255, 255)

    -- render option 2 blue if we're highlighting that one
    if highlighted == 2 then
        love.graphics.setColor**(0, 255, 255, 255)**
    end
    love.graphics.printf("HIGH SCORES", 0, VIRTUAL_HEIGHT / 2 + 90,
        VIRTUAL_WIDTH, 'center')

    -- reset the color
    love.graphics.setColor(255, 255, 255, 255)
end

**Comment by RobotWizard11** [comment]
Thank you!!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
